from setuptools import setup, find_packages

setup(
    name="tess-terminal-pro",
    version="5.0.0",
    description="The Hybrid AI Terminal Agent",
    author="Rohit Kumar",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "openai>=1.10.0",
        "groq>=0.4.0",
        "google-generativeai>=0.3.0",
        "chromadb>=0.4.22",
        "pydantic>=2.0.0",
        "python-dotenv>=1.0.0",
        "requests>=2.31.0",
        "beautifulsoup4>=4.12.0",
        "playwright>=1.40.0",
        "pyautogui>=0.9.54",
        "psutil>=5.9.0",
        "watchdog>=3.0.0",
        "pathspec>=0.11.0",
        "sounddevice>=0.4.6",
        "scipy>=1.11.0",
        "openai-whisper>=20231117",
        "schedule",
        "duckduckgo-search>=6.0.0",
        "rich>=13.0.0",
        "win11toast>=0.33",
        "fpdf2>=2.7.0",
        "python-pptx>=0.6.21",
        "pymupdf>=1.23.0",
        "python-telegram-bot>=20.0",
        "docker>=7.0.0",
        "clipboard>=0.0.4",
        "youtube-search-python>=1.6.6",
        "screen-brightness-control>=0.8.0",
        "google-api-python-client>=2.0.0",
        "google-auth-oauthlib>=1.0.0",
        "google-auth-httplib2>=0.1.0"
    ],
    entry_points={
        'console_scripts': [
            'tess=tess_cli.cli:main',
        ],
    },
)
