import json
import re
import time
from datetime import datetime
import warnings
import logging
import random


# Suppress warnings
warnings.filterwarnings("ignore", category=FutureWarning)
import google.generativeai as genai
from groq import Groq
from openai import OpenAI

from .config import Config
from .logger import setup_logger
from .memory_engine import MemoryEngine
from .cognitive_brains import (
    ReflexBrain,
    TaskBrain,
    MemoryBrain,
    VisionBrain,
    PlannerBrain,
    SocialBrain,
    SecurityBrain,
)
from .event_bus import event_bus
from .cognitive_layers import CognitiveRouter

logger = setup_logger("Brain")

class LLMClientFactory:
    """Factory to create LLM clients."""
    @staticmethod
    def get_client(provider, model, api_key):
        if not api_key: return None, f"Missing API Key for {provider}"
        try:
            if provider == "groq": return Groq(api_key=api_key), None
            elif provider == "openai": return OpenAI(api_key=api_key), None
            elif provider == "deepseek": return OpenAI(api_key=api_key, base_url="https://api.deepseek.com"), None
            elif provider == "ollama": return OpenAI(api_key=api_key or "ollama", base_url="http://localhost:11434/v1"), None
            elif provider == "gemini":
                genai.configure(api_key=api_key)
                return genai.GenerativeModel(model), None
        except Exception as e:
            return None, str(e)
        return None, "Unknown Provider"

class Brain:
    """
    Handles LLM interactions with robust retries and failover.
    """
    def __init__(self, user_id="default", knowledge_db=None, personality="casual"):
        self.user_id = str(user_id)
        self.personality = personality
        self.history = [{"role": "system", "content": Config.get_system_prompt(personality)}]
        
        self.memory = MemoryEngine(user_id=self.user_id)
        self.knowledge_db = knowledge_db 
        self.provider = Config.LLM_PROVIDER
        self.model = Config.LLM_MODEL
        self.current_key_index = 0

        self.reflex_brain = ReflexBrain()
        self.task_brain = TaskBrain(self)
        self.memory_brain = MemoryBrain(self)
        self.vision_brain = VisionBrain(self)
        self.planner_brain = PlannerBrain(self)
        self.social_brain = SocialBrain()
        self.security_brain = SecurityBrain()

        # Initialize Cognitive Router and Habit active states
        self.router = CognitiveRouter(self)
        self.active_habit_graph = None
        self.active_habit_step_idx = 0
        
        # Track session activities for daily summaries and RAG
        self.session_events = []
        
        logger.info(f"Brain Initialized | Provider: {self.provider.upper()} | Model: {self.model}")

    def update_history(self, role, content):
        self.history.append({"role": role, "content": content})
        
        # Track session activities for daily summaries and preference RAG
        if not hasattr(self, "session_events"):
            self.session_events = []
        if role == "user":
            self.session_events.append(f"User Query: {content}")
        elif role == "system" and "Result of " in str(content):
            self.session_events.append(f"System: {content}")
        elif role == "assistant":
            try:
                action_data = json.loads(content)
                action_name = action_data.get("action")
                if action_name and action_name not in ("reply_op", "final_reply"):
                    self.session_events.append(f"TESS Action: {action_name}")
            except:
                pass

        # Phase 2 — Event-Driven Cognition: Publish events on history update
        if role == "user":
            event_bus.publish("user_query_received", content)
        elif role == "system" and hasattr(self, "router") and self.router.procedural_learner.last_query:
            # Capture last action generated by assistant to bind with its result
            last_action = {}
            for msg in reversed(self.history):
                if msg["role"] == "assistant":
                    try:
                        last_action = json.loads(msg["content"])
                        break
                    except Exception:
                        pass
            if last_action:
                event_data = dict(last_action)
                event_data["result"] = content
                event_bus.publish("command_executed", event_data)

    def request_vision(self, image_path: str, prompt: str) -> str:
        """
        Send a screenshot/image to the vision-capable LLM and return its analysis.
        Supports Gemini (natively multimodal) and OpenAI-compatible vision models.

        Args:
            image_path: Absolute path to the screenshot PNG/JPG file.
            prompt: What to ask about the image.

        Returns:
            str: The model's plain-text description/analysis of the image.
        """
        return self.vision_brain.analyze_image(image_path, prompt)

    def _get_client(self):
        key = Config.get_api_key(self.provider, index=self.current_key_index)
        return LLMClientFactory.get_client(self.provider, self.model, key)

    def _call_api_with_retry(self, messages, json_mode=False, temperature=0.7, max_retries=5):
        """Centralized API caller with exponential backoff."""
        for attempt in range(max_retries):
            client, err = self._get_client()
            if not client:
                logger.error(f"Client Init Error: {err}")
                return None

            try:
                # Gemini
                if self.provider == "gemini":
                    prompt = "\n".join([f"{m['role']}: {m['content']}" for m in messages])
                    # JSON mode hack for Gemini
                    if json_mode and "json" not in prompt.lower(): 
                        prompt += "\nOutput strict JSON."
                    
                    # Only disable safety rails for the explicit "rogue" persona.
                    # Autonomous coding mode does NOT need content filters removed.
                    if self.personality == "rogue":
                        safety_settings = [
                            {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
                            {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
                            {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"},
                            {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"}
                        ]
                        response = client.generate_content(prompt, safety_settings=safety_settings)
                    else:
                        response = client.generate_content(prompt)
                    return response.text

                # OpenAI / Groq / DeepSeek / Ollama
                args = {
                    "model": self.model,
                    "messages": messages,
                    "temperature": temperature
                }
                if json_mode: args["response_format"] = {"type": "json_object"}
                
                completion = client.chat.completions.create(**args)
                return completion.choices[0].message.content

            except Exception as e:
                err_msg = str(e).lower()
                logger.warning(f"API Attempt {attempt+1} Failed: {err_msg}")
                
                # Rate Limits (429) or Overloaded (503)
                if "429" in err_msg or "resource exhausted" in err_msg:
                    sleep_time = (2 ** attempt) + random.uniform(0, 1) # 1s, 2s, 4s, 8s...
                    logger.info(f"Rate limit hit. Sleeping {sleep_time:.2f}s...")
                    time.sleep(sleep_time)
                    # Rotate key for next attempt
                    self.current_key_index += 1
                    continue
                
                # JSON Errors
                if "json" in err_msg and json_mode:
                    messages.append({"role": "user", "content": "Previous response was invalid JSON. Retrying."})
                    continue

                # Provider Failover Logic could go here
                
        logger.error("Max retries exceeded.")
        self.current_key_index = 0
        return None

    def think(self, prompt):
        """Simple thought generation."""
        return self.request_completion([{"role": "user", "content": prompt}]) or "Thinking failed."

    def request_completion(self, messages, json_mode=False, temperature=0.7):
        """Public method for one-off completions."""
        return self._call_api_with_retry(messages, json_mode, temperature)

    def summarize_and_save_session(self):
        """Generates a summary of the session activities and saves it to RAG database."""
        if not hasattr(self, "session_events") or not self.session_events:
            return
        
        logger.info("Summarizing session activities...")
        events_log = "\n".join(self.session_events)
        
        # 1. Generate Activity Summary
        prompt = (
            "You are a meta-cognition analyzer. Summarize the following session of user queries "
            "and assistant actions into a concise 2-3 sentence diary entry of what was accomplished today. "
            "Do not output JSON or markdown backticks, just the plain text summary.\n\n"
            f"Session Log:\n{events_log}"
        )
        
        try:
            summary = self.request_completion([{"role": "user", "content": prompt}])
            if summary and "thinking" not in summary.lower():
                summary = summary.strip()
                if self.knowledge_db:
                    self.knowledge_db.store_memory(
                        f"On {datetime.now().strftime('%Y-%m-%d %H:%M')}, user activities: {summary}",
                        metadata={"type": "daily_summary", "timestamp": datetime.now().isoformat()}
                    )
                    logger.info("Saved daily activity summary to RAG database.")
        except Exception as e:
            logger.error(f"Failed to generate/save session summary: {e}")

        # 2. Extract User Facts and Preferences
        extract_prompt = (
            "Analyze the following conversation log and extract any concrete facts, details, or preferences "
            "the user mentioned about themselves (e.g. name, work, interests, habits, styling preferences, tools liked). "
            "Format the output as a JSON list of strings, e.g. ['likes Python', 'prefers dark theme', 'has a friend named Ashi']. "
            "If no new facts were mentioned, return an empty list [].\n\n"
            f"Conversation Log:\n{events_log}"
        )
        try:
            facts_json = self.request_completion([{"role": "user", "content": extract_prompt}], json_mode=True)
            if facts_json:
                facts = self._parse_json(facts_json)
                if isinstance(facts, dict):
                    # Sometimes the LLM returns an object with a key like "facts" instead of a flat list
                    facts = facts.get("facts", []) or facts.get("preferences", []) or list(facts.values())
                
                if isinstance(facts, list):
                    from .user_profile import UserProfile
                    profile = UserProfile()
                    count = 0
                    for fact in facts:
                        if isinstance(fact, str) and len(fact.strip()) > 3:
                            if profile.learn_fact(fact.strip(), source="llm_session_extract"):
                                count += 1
                    logger.info(f"Extracted and saved {count} new user facts.")
        except Exception as e:
            logger.error(f"Failed to extract preferences: {e}")

    def generate_command(self, user_query):
        """Main chat loop entry point with Event-Driven and Cognitive Routing layers."""
        # Record query for procedural habit learning
        self.router.procedural_learner.record_query(user_query)

        # 1. Cognitive Layer Classification
        layer = self.router.route(user_query)
        logger.info(f"Cognitive Routing | Query: '{user_query}' | Layer: {layer.upper()}")

        # Print visual pathway visualizer in terminal (if UI is not minimal)
        try:
            from .terminal_ui import print_cognitive_flow
            print_cognitive_flow(user_query, layer, details=self.router.procedural_learner.find_learned_workflow(user_query) if layer == "habit" else None)
        except Exception as e:
            logger.warning(f"Failed to render cognitive visualizer: {e}")

        # Update prompt dynamically to provide temporary cognition context (Phase 3)
        self.history[0]["content"] = self.router.get_temporary_cognition_context(layer, Config.get_system_prompt(self.personality))

        # 2. Layer 1: Reflex Layer (deterministic shortcuts)
        if layer == "reflex":
            reflex_cmd = self.router.last_reflex_result
            if reflex_cmd:
                self.history.append({"role": "user", "content": user_query})
                self.history.append({"role": "assistant", "content": json.dumps(reflex_cmd)})
                # Immediately complete single-step habit
                self.router.procedural_learner.commit_episode(success=True)
                return reflex_cmd

        # 3. Layer 2: Habit Layer (cached procedural graphs)
        if layer == "habit" or self.active_habit_graph is not None:
            if self.active_habit_graph is None:
                self.active_habit_graph = self.router.procedural_learner.find_learned_workflow(user_query)
                self.active_habit_step_idx = 0
                logger.info(f"Executing compiled habit graph: '{self.active_habit_graph.get('name')}'")

            if self.active_habit_graph is not None:
                steps = self.active_habit_graph["steps"]
                if self.active_habit_step_idx < len(steps):
                    step = dict(steps[self.active_habit_step_idx])
                    self.active_habit_step_idx += 1
                    
                    # Embed step explanation into thought
                    step["thought"] = f"[HABIT INSTINCT] Executing step {self.active_habit_step_idx}/{len(steps)} of cached workflow '{self.active_habit_graph['name']}'."
                    
                    # Append history to maintain conversational continuity
                    if self.active_habit_step_idx == 1:
                        self.history.append({"role": "user", "content": user_query})
                    self.history.append({"role": "assistant", "content": json.dumps(step)})

                    # Publish command executed event for self-reflection & logging
                    event_bus.publish("command_executed", step)

                    # Wrap up habit if last step executed
                    if self.active_habit_step_idx >= len(steps):
                        self.active_habit_graph = None
                        self.active_habit_step_idx = 0
                    
                    return step

        # 4. Layer 3 & 4: Planner & Deep Reasoner layers
        cmd = self.task_brain.generate_command(user_query)

        # Record if this operation completes an execution episode to store habits
        if cmd.get("action") in ("final_reply", "reply_op"):
            self.router.procedural_learner.commit_episode(success=True)

        return cmd

    def _parse_json(self, text):
        try:
            # 1. Strip Markdown Code Blocks
            clean = text
            if "```" in clean:
                # Extract content inside the first code block
                pattern = r"```(?:json)?\s*(.*?)\s*```"
                match = re.search(pattern, clean, re.DOTALL)
                if match:
                    clean = match.group(1)
            
            clean = clean.strip()
            
            # 2. Try Standard Decode (handles trailing data via raw_decode)
            obj = None
            try:
                obj, _ = json.JSONDecoder().raw_decode(clean)
            except:
                pass

            # 3. Brace-counting fallback — walks the string to find the full JSON object
            if obj is None:
                start_idx = clean.find('{')
                if start_idx != -1:
                    try:
                        brace_count = 0
                        for i in range(start_idx, len(clean)):
                            if clean[i] == '{': brace_count += 1
                            elif clean[i] == '}': brace_count -= 1
                            if brace_count == 0:
                                obj = json.loads(clean[start_idx:i+1])
                                break
                    except Exception:
                        pass

            # 4. If we got a parsed object, normalize the action field
            if isinstance(obj, dict):
                action = obj.get("action")
                # Guard: coerce non-string action values (nested dicts, lists) to reply_op
                if action is not None and not isinstance(action, str):
                    logger.warning(f"LLM returned non-string action type: {type(action).__name__}. Coercing to reply_op.")
                    obj["action"] = "reply_op"
                    obj.setdefault("content", str(action))
                return obj

            return {"action": "reply_op", "content": text} # Fallback to chat
        except Exception as e:
            logger.error(f"JSON Parse fail: {e}")
            return {"action": "reply_op", "content": text}
